const SEVERITIES=["LOW","MEDIUM","HIGH","CRITICAL"],STATUSES=["OPEN","INVESTIGATING","RESOLVED"];
let incidents=JSON.parse(localStorage.getItem("chainshield_incidents")||"[]");
const $=id=>document.getElementById(id);
function save(){localStorage.setItem("chainshield_incidents",JSON.stringify(incidents));render()}
function seed(){incidents=[{id:"DEMO-001",title:"High-value transfer anomaly",severity:2,status:0,hash:"0x7e91...a21f",time:"Today 14:32"},{id:"DEMO-002",title:"Repeated failed authentication",severity:1,status:1,hash:"0x8b10...4d92",time:"Today 13:11"},{id:"DEMO-003",title:"Known malicious contract interaction",severity:3,status:2,hash:"0xc20d...91aa",time:"Yesterday 22:48"}];save()}
function render(){const open=incidents.filter(x=>x.status!==2).length,critical=incidents.filter(x=>x.severity===3&&x.status!==2).length,resolved=incidents.filter(x=>x.status===2).length;$("openCount").textContent=open;$("criticalCount").textContent=critical;$("resolvedCount").textContent=resolved;$("hashCount").textContent=incidents.filter(x=>x.hash).length;$("systemRisk").textContent=Math.min(99,30+critical*18+open*4);$("incidents").innerHTML=incidents.length?incidents.map(i=>`<div class="incident"><div class="severity ${SEVERITIES[i.severity]}">${SEVERITIES[i.severity]}</div><div><strong>${escapeHtml(i.title)}</strong><div class="muted">${i.time||"Local event"} · ${i.hash||"No hash"}</div></div><div class="pill">${STATUSES[i.status]}</div></div>`).join(""):"<div class=\"muted\">No incidents. Load demo incidents or register one.</div>"}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function sha256(text){const data=new TextEncoder().encode(text),hash=await crypto.subtle.digest("SHA-256",data);return[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function encrypt(text){const key=await crypto.subtle.generateKey({name:"AES-GCM",length:256},true,["encrypt"]),iv=crypto.getRandomValues(new Uint8Array(12)),encoded=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,new TextEncoder().encode(text)),rawKey=await crypto.subtle.exportKey("raw",key),b64=x=>btoa(String.fromCharCode(...new Uint8Array(x)));return{ciphertext:b64(encoded),iv:b64(iv),key:b64(rawKey)}}
$("seedBtn").onclick=seed;
$("hashBtn").onclick=async()=>{const text=$("evidenceInput").value.trim();if(!text)return $("cryptoOutput").textContent="Enter evidence first.";const hash=await sha256(text);$("cryptoOutput").textContent="SHA-256\n"+hash+"\n\nbytes32-compatible\n0x"+hash};
$("encryptBtn").onclick=async()=>{const text=$("evidenceInput").value.trim();if(!text)return $("cryptoOutput").textContent="Enter a note first.";$("cryptoOutput").textContent=JSON.stringify(await encrypt(text),null,2)};
$("analyzeBtn").onclick=()=>{const value=Number($("valueInput").value)||0,failed=Number($("failedInput").value)||0,address=$("walletInput").value.trim();let score=10,reasons=[];if(value>5){score+=30;reasons.push("large transfer value")}else if(value>1){score+=15;reasons.push("elevated transfer value")}if(failed>=5){score+=35;reasons.push("high failed-transaction count")}else if(failed>=2){score+=18;reasons.push("repeated failures")}if(address&&!/^0x[a-fA-F0-9]{40}$/.test(address)){score+=20;reasons.push("malformed wallet address")}score=Math.min(100,score);const level=score>=75?"CRITICAL":score>=50?"HIGH":score>=30?"MEDIUM":"LOW";$("riskResult").classList.remove("hidden");$("riskResult").innerHTML=`<strong>${level} · ${score}/100</strong><br><span class="muted">${reasons.length?reasons.join(" · "):"No significant risk signals detected."}</span>`};
$("registerBtn").onclick=async()=>{const title=$("titleInput").value.trim(),sev=Number($("severityInput").value);let hash=$("evidenceHashInput").value.trim();if(!title)return $("chainStatus").textContent="Enter an incident title.";if(!hash)hash="0x"+await sha256(title+Date.now());incidents.unshift({id:"LOCAL-"+Date.now(),title,severity:sev,status:0,hash:hash.slice(0,18)+"...",time:new Date().toLocaleString()});save();$("chainStatus").textContent="Incident added to the local SOC timeline. Connect a deployed contract to make it on-chain."};
$("connectBtn").onclick=async()=>{if(!window.ethereum)return alert("MetaMask was not detected. The dashboard still works in demo mode.");try{const accounts=await window.ethereum.request({method:"eth_requestAccounts"});$("network").textContent=accounts[0].slice(0,6)+"..."+accounts[0].slice(-4);$("connectBtn").textContent="Wallet Connected"}catch(e){$("chainStatus").textContent="Wallet connection cancelled."}};
render();